# Generated by Django 5.0.7 on 2026-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фото проекта',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='projects/covers/', verbose_name='Обложка')),
                ('category', models.CharField(choices=[('prep', 'Подготовка'), ('repair', 'Ремонт'), ('tuning', 'Тюнинг'), ('service', 'Обслуживание')], default='prep', max_length=32, verbose_name='Категория')),
                ('vehicle', models.CharField(blank=True, max_length=255, verbose_name='Модель автомобиля')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('gallery', models.ManyToManyField(blank=True, related_name='projects', to='projects.projectimage', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
