# Generated by Django 5.0.7 on 2026-03-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_servicegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=255, verbose_name='Модель и год')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Письмо отправлено')),
                ('email_error', models.TextField(blank=True, verbose_name='Ошибка отправки почты')),
            ],
            options={
                'verbose_name': 'Заявка с сайта',
                'verbose_name_plural': 'Заявки с сайта',
                'ordering': ['-created_at'],
            },
        ),
    ]
