# Generated by Django 5.0.7 on 2026-03-23 01:58

from django.db import migrations, models


DEFAULT_MAP_EMBED = (
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2245.371342371511"
    "!2d37.534411316046484!3d55.75581448055152!2m3!1f0!2f0!3f0!3m2!1i1024!2i768"
    "!4f13.1!3m3!1m2!1s0x46b54bd6ed0f2c73%3A0x69687e1f40d86161!2z0JrRg9GC0YPQt9C-"
    "0LLRgdC60LjQuSDQv9GALdGCLiwgMzYsIE1vc2t2YSwgMTIxMTcw!5e0!3m2!1sru!2sru"
    "!4v1650000000000!5m2!1sru!2sru"
)


def seed_contact_settings(apps, schema_editor):
    ContactSettings = apps.get_model("projects", "ContactSettings")
    if ContactSettings.objects.exists():
        return
    ContactSettings.objects.create(
        email="info@pickupservice.ru",
        phone_display="+7 999 000 00 00",
        phone_tel="+79990000000",
        telegram_url="",
        whatsapp_url="",
        vk_url="",
        map_embed_url=DEFAULT_MAP_EMBED,
        coordinates_label="55.7558° N, 37.5366° E",
    )


def unseed_contact_settings(apps, schema_editor):
    ContactSettings = apps.get_model("projects", "ContactSettings")
    ContactSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_bookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_display', models.CharField(help_text='Например: +7 999 000 00 00', max_length=64, verbose_name='Телефон (отображение)')),
                ('phone_tel', models.CharField(help_text='Без префикса tel:, например +79990000000', max_length=32, verbose_name='Телефон для ссылки tel:')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('vk_url', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('map_embed_url', models.TextField(help_text='Полная ссылка из «Поделиться» → «Встроить карту» (Google, Яндекс и т.д.).', verbose_name='URL встраивания карты (iframe src)')),
                ('coordinates_label', models.CharField(blank=True, max_length=128, verbose_name='Подпись координат')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контакты на сайте',
                'verbose_name_plural': 'Контакты на сайте',
            },
        ),
        migrations.RunPython(seed_contact_settings, unseed_contact_settings),
    ]
