# Generated by Django 5.0.7 on 2026-03-23

from django.db import migrations, models


def seed_testimonials(apps, schema_editor):
    Testimonial = apps.get_model("projects", "Testimonial")
    if Testimonial.objects.exists():
        return
    rows = [
        {
            "quote": (
                "Ребята из Пикапсервис превратили мой обычный крузак в настоящего монстра "
                "бездорожья. Качество сварных швов и внимание к деталям просто поражают. "
                "Прошел Кольский полуостров без единой поломки."
            ),
            "author_name": "Алексей Смирнов",
            "car": "Toyota Land Cruiser 200",
            "order": 0,
        },
        {
            "quote": (
                "Идеальная работа с подвеской. Машина перестала 'козлить' на грейдере, "
                "а энергоемкость теперь позволяет не сбрасывать газ там, где остальные ползут. "
                "Лучший сервис для подготовки."
            ),
            "author_name": "Дмитрий Волков",
            "car": "Nissan Patrol Y61",
            "order": 1,
        },
        {
            "quote": (
                "Делали полный ребилд салона и устанавливали спальник с органайзером. "
                "Теперь в экспедициях сплю как дома, все вещи на своих местах. "
                "Очень грамотный инженерный подход."
            ),
            "author_name": "Михаил Захаров",
            "car": "Toyota Hilux",
            "order": 2,
        },
    ]
    for row in rows:
        Testimonial.objects.create(published=True, **row)


def unseed_testimonials(apps, schema_editor):
    Testimonial = apps.get_model("projects", "Testimonial")
    Testimonial.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_fix_contact_map_embed_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(verbose_name="Текст отзыва")),
                ("author_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("car", models.CharField(max_length=255, verbose_name="Автомобиль")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Отзыв на главной",
                "verbose_name_plural": "Отзывы на главной",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.RunPython(seed_testimonials, unseed_testimonials),
    ]
