# Generated by Django 5.0.7 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=64, verbose_name="Телефон")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Письмо отправлено"),
                ),
                (
                    "email_error",
                    models.TextField(blank=True, verbose_name="Ошибка отправки почты"),
                ),
            ],
            options={
                "verbose_name": "Заявка на звонок",
                "verbose_name_plural": "Заявки на звонок",
                "ordering": ["-created_at"],
            },
        ),
    ]

