# Generated by Django 5.0.7 on 2026-03-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_callbackrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('booking', 'Заявка «Запись»'), ('callback', 'Заявка «Звонок»')], max_length=32, verbose_name='Тип заявки')),
                ('target_chat_id', models.BigIntegerField(verbose_name='Куда отправить (chat_id)')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('booking_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_outbox_messages', to='projects.bookingrequest', verbose_name='Заявка «Запись»')),
                ('callback_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_outbox_messages', to='projects.callbackrequest', verbose_name='Заявка «Звонок»')),
            ],
            options={
                'verbose_name': 'Outbox: Telegram сообщение',
                'verbose_name_plural': 'Outbox: Telegram сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='projects_te_status_d6d612_idx'), models.Index(fields=['request_type', '-created_at'], name='projects_te_request_fda6ba_idx'), models.Index(fields=['target_chat_id', '-created_at'], name='projects_te_target__cbb302_idx')],
            },
        ),
    ]
