# Generated by Django 5.0.7 on 2026-03-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_yandexsynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPreparationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects/preparation-stages/', verbose_name='Фото (необязательно)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_stages', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап подготовки (проекта)',
                'verbose_name_plural': 'Этапы подготовки (проекта)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
