# Generated by Django 5.0.7 on 2026-04-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectpreparationstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='novelties/', verbose_name='Фото')),
                ('starts_at', models.DateTimeField(verbose_name='Время запуска предложения')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание предложения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новинки',
                'ordering': ['order', '-starts_at', '-created_at'],
            },
        ),
    ]
